from datetime import datetime
from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


def build_prediction_pdf(applicant: dict, prediction_label: str, confidence: float) -> bytes:
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36)
    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph("Loan Approval Prediction Report", styles["Title"]))
    story.append(Paragraph(datetime.now().strftime("Generated on %Y-%m-%d %H:%M"), styles["Normal"]))
    story.append(Spacer(1, 16))

    summary = [
        ["Prediction", prediction_label],
        ["Confidence", f"{confidence:.1%}"],
    ]
    summary_table = Table(summary, colWidths=[130, 320])
    summary_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#E8EEF7")),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#B8C2D6")),
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("PADDING", (0, 0), (-1, -1), 8),
            ]
        )
    )
    story.append(summary_table)
    story.append(Spacer(1, 18))

    story.append(Paragraph("Applicant Details", styles["Heading2"]))
    rows = [["Field", "Value"]] + [[key, str(value)] for key, value in applicant.items()]
    details_table = Table(rows, colWidths=[190, 260])
    details_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#243B53")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#C9D2E3")),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("PADDING", (0, 0), (-1, -1), 7),
            ]
        )
    )
    story.append(details_table)
    story.append(Spacer(1, 14))
    story.append(
        Paragraph(
            "This report is generated by an educational machine-learning model and should support, not replace, responsible human review.",
            styles["Italic"],
        )
    )

    doc.build(story)
    return buffer.getvalue()

